### PR TITLE
LocalStorage + FileSystemAccess file systems

### PR DESCRIPTION
**Pull request by DavidSouther**
This introduces a "Chained" FileSystemAdapter that allows using a FileSystemAccessFileSystemAdapter and a LocalStorageAdapter together. For reads, it will attempt to read from the FileSystemAccess, and use LocalStorage if it isn't found. For writes, it writes to both. To get this, you need to affirmatively choose a folder, you do this via the "Use Local FileSystem" settings option. (This needs to be selected every page load at this point.)

### CODE REVIEW

**Comment by DavidSouther** [comment]
image


image


image

image

**Comment by AndyPro720** [comment]
As of now, there's no way to upload from local fs on the published IDE right?

**Comment by DavidSouther** [comment]
> As of now, there's no way to upload from local fs on the published IDE right?

Correct, and this PR is our first attempt at resolving that.

**Comment by AndyPro720** [comment]
On a side note, is there any way to scale up/zoom the java VM emulator screen like on the IDE for ease of dev?

**Comment by DavidSouther** [comment]
Yes, the x0, x1, and x2 buttons on the top-right of the screen:

image

image

**Comment by AndyPro720** [comment]
@DavidSouther I was asking for a similar ease of use function/workaround on the Java VM emulator.  It's real handy on the IDE but I'm currently dev on local fs.

**Comment by DavidSouther** [comment]
Ah, sorry, I got your question backwards. No, at this time, that is a feature that we've been able to add to the web version, and I don't anticipate we will be doing any updates to the Java version.

**Review by netalondon — APPROVED** [review]

**Pull request merged**
