### PR TITLE
Fix compiler page offset when having too much tabs

### LINKED ISSUE #451: [bug]: Jack compiler - page slides after using a slider and clicking on a tab when there are a lot of files
### Tool

None

### Interface

None

### Contact Details

_No response_

### What happened?

I have many files. When I use horizontal slider and click on last tab page slides
Screenshot from 2024-09-11 09-41-27

### Additional Comments

_No response_

### Do you want to try to fix this bug?

- [ ] I want to try to add this feature!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by netalondon**
Fixes #451 

the line ` position: absolute !important;` caused the issue.
`disply: none;` achieves the same effect.

### CODE REVIEW

**Comment by DavidSouther** [comment]
Unfortunately, this breaks keyboard interactions. The current form allows keyboard focus on the tabs to use the arrow keys to move tabs.

**Comment by netalondon** [comment]
We can do `opacity: 0;` instead, but this leaves a small gap after the label.

before:
Screenshot from 2024-09-16 18-04-16

after:
Screenshot from 2024-09-16 18-04-22

Is this good enough?

**Comment by DavidSouther** [comment]
How does it look by removing the `position: absolute` and setting `opacity: 0; margin-inline: -1px;`?

**Comment by netalondon** [comment]
> How does it look by removing the `position: absolute` and setting `opacity: 0; margin-inline: -1px;`?

There's still a gap but smaller:
Screenshot from 2024-09-16 19-01-19


`margin-inline: -7px;` looks most similar to the initial version.
Should I just do that?

**Comment by DavidSouther** [comment]
It makes me a tiny bit uncomfortable, but just add a comment explaining why it's that way.

**Review by DavidSouther — APPROVED** [review]

**Pull request merged**
